### ISSUE TITLE
I have some question about integration_test/step_3_run

### ISSUE THREAD

**Issue by stevebobaaa** [snkas/hypatia#19]
When I run hypatia_run_test, the following error occurs at integration_test/step_3_run :

Traceback (most recent call last):
  File "step_3_run.py", line 35, in <module>
    if local_shell.count_screens() != 0:
  File "/home/jkc/.local/lib/python3.8/site-packages/exputil/shell.py", line 207, in count_screens
    res = self.valid_exec("screen -ls")
  File "/home/jkc/.local/lib/python3.8/site-packages/exputil/shell.py", line 203, in valid_exec
    self._raise_if_invalid(res)
  File "/home/jkc/.local/lib/python3.8/site-packages/exputil/shell.py", line 150, in _raise_if_invalid
    raise InvalidCommandError(res.output, res)
exputil.shell.InvalidCommandError: ('/bin/sh: 1: screen: not found\n', <exputil.shell.ShellExecResult object at 0x7f22c766a130>)

Thank you in advance!!

**Comment by watalou** [comment]
I also have encountered this problem.

**Comment by snkas** [comment]
Please see: https://github.com/snkas/exputilpy/issues/2

**Comment by stevebobaaa** [comment]
> Please see: [snkas/exputilpy#2](https://github.com/snkas/exputilpy/issues/2)

Thank you so much !!!
